Improvement: Documentation
BESTSELLER/nightscaler pull request #42
Opened 2023-05-30 09:18 UTC by OrKarstoft

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

No documentation.

Issue Number: Resolves #40 

## What is the new behavior?

- Documentation

## Other information

2023-05-30 09:19 UTC, OrKarstoft commented
Missing documentation on how to install.

Helm is the only installation to be documented for now.

2023-11-21 21:38 UTC, Andrei-Predoiu approved these changes

2024-05-22 20:52 UTC, brondum requested changes

2024-05-22 20:52 UTC, brondum commented on README.md
> +on Pub/Sub messages. It serves as an extension to kube-downscaler, providing
```suggestion
on Pub/Sub messages. It serves as an extension to [kube-downscaler](https://codeberg.org/hjacobs/kube-downscaler), providing
```

2024-05-22 20:53 UTC, brondum approved these changes

2024-05-22 20:58 UTC, merged